Repository gojue/ecapture, pull requests merged in 2022-06, with the labels that each got.

#68 fix some typos
  README.md
  kern/bpf/bpf_helper_defs.h
  pkg/util/kernel/kernel_version.go
  user/imodule.go
Labels: documentation, good first issue

#70 Add nosearch argument to skip auto search lib path
  cli/cmd/global.go
  cli/cmd/root.go
  cli/cmd/tls.go
  user/common.go
  user/config_gnutls.go
  user/config_nspr.go
  user/config_openssl.go
  user/iconfig.go
Labels: bug

#86 New feature: #85 event filter by uid for module tls
  cli/cmd/tls.go
  kern/bash_kern.c
  kern/gnutls_kern.c
  kern/nspr_kern.c
  kern/openssl_kern.c
  user/probe_openssl.go
Labels: enhancement

#94 New Feature: #79 Auto release for android gki
  .github/workflows/codeql-analysis.yml
  .github/workflows/go-c-cpp.yml
  .github/workflows/release.yml
  Makefile
  builder/Makefile.release
Labels: enhancement

#107 New Feature: support Android without GKI (kernel version > 4.18)
  .github/workflows/go-c-cpp.yml
  cli/cmd/mysqld.go
  cli/cmd/postgres.go
  cli/cmd/root.go
  main.go
  pkg/util/ebpf/bpf.go
  pkg/util/ebpf/bpf_androidgki.go
  pkg/util/ebpf/bpf_linux.go
  user/common.go
  user/common_androidgki.go
  user/common_linux.go
  user/config_gnutls.go
  user/config_gnutls_androidgki.go
  user/config_gnutls_linux.go
  user/config_mysqld.go
  user/config_nspr.go
  user/config_nspr_androidgki.go
  user/config_nspr_linux.go
  user/config_openssl.go
  user/config_openssl_androidgki.go
  user/config_openssl_linux.go
  user/config_postgres.go
  user/event_mysqld.go
  user/event_postgres.go
  user/probe_mysqld.go
  user/probe_postgres.go
Labels: enhancement
