Repository gojue/ecapture, pull requests merged in 2022-09, with the labels that each got.

#193 kern: get ssl_session in the `*SSL_get_session()` order .
  kern/masterkey_kern.h
  user/module/probe_openssl_tc.go
Labels: bug, fix

#209 feat: add support TLSv1.3 decryption
  kern/masterkey_kern.h
  pkg/util/hkdf/hkdf.go
  pkg/util/hkdf/hkdf_test.go
  user/module/probe_openssl.go
Labels: bug

#217 user/module : use const for SSL masterKey function hook.
  user/module/const_androidgki.go
  user/module/const_linux.go
  user/module/probe_openssl_tc.go
Labels: fix

#223 kern: rodata map not supported on kernel 4.19 or older
  kern/common.h
  kern/openssl_tc.h
Labels: bug, fix
