Repository gojue/ecapture, pull requests merged in 2023-01, with the labels that each got.

#288 fix(gossl): invalid memory address or nil pointer
  user/module/probe_gossl.go
Labels: bug, fix

#295 pkg: get GoVersion by `buildinfo` package from ELF (by golang compiled) (#262)
  pkg/proc/proc.go
Labels: bug, fix

#298 fixes supported kernel version on arm64(aarch64). (#296)
  README.md
  README_CN.md
  cli/cmd/tls.go
  main.go
Labels: documentation

#299 user: fixes slice bounds out of range bug (#297)
  user/event/event_gossl.go
Labels: bug, fix

#302 kern: fixes constant value of type uint64. (#301)
  kern/common.h
  user/module/probe_bash.go
Labels: bug
