Repository gojue/ecapture, pull requests merged in 2024-08, with the labels that each got.

#583 pkg: add http2 request/response unit test.
  pkg/event_processor/http2_request_test.go
  pkg/event_processor/http2_response.go
  pkg/event_processor/http2_response_test.go
  pkg/event_processor/http_response_test.go
  pkg/event_processor/processor_test.go
Labels: test, improve

#586 feat: allow capture ipv6 packet
  Makefile
  kern/common.h
  kern/ecapture.h
  kern/tc.h
Labels: enhancement

#589 workflows: remove Qodana CI workflow.
  .github/workflows/code_quality.yml
  builder/init_env.sh
Labels: fix, test

#593 fix: fix undeclared identifier error when make in debug mode
  kern/tc.h
Labels: bug

#607 user: adjusted the timing of the display of the kernel version is too low
  user/module/imodule.go
Labels: bug, fix

#606 kern: support uid/pid filter in ebpf TC hook.
  kern/mysqld_kern.c
  kern/postgres_kern.c
  kern/tc.h
  user/module/probe_openssl_pcap.go
Labels: bug, fix

#613 fix: fallback to default version with warn
  user/module/probe_openssl_lib.go
Labels: improve
