Repository gojue/ecapture, pull requests merged in 2024-12, with the labels that each got.

#672 fix MariaDB typo in README.md
  README.md
Labels: documentation

#677 Add a reminder for failure when hooking libnss3.so.
  cli/cmd/nspr.go
  cli/cmd/root.go
  user/module/probe_nspr.go
Labels: documentation, fix

#679 Fix the version number string cannot be found in the dynamic library of boringssl.
  .github/workflows/release.yml
  cli/cmd/root.go
  cli/cmd/tls.go
  user/module/probe_openssl.go
  user/module/probe_openssl_lib.go
Labels: 🐞 bug, fix

#680 fix: pcap filter not work as expected
  kern/tc.h
Labels: 🐞 bug, fix

#683 [feat] support capture zsh command
  README.md
  builder/rpmBuild.spec
  cli/cmd/zsh.go
  kern/common.h
  kern/zsh_kern.c
  user/config/config_zsh.go
  user/event/event_zsh.go
  user/module/const.go
  user/module/probe_zsh.go
  variables.mk
Labels: enhancement

#681 feat: detect CAP_BPF
  cli/cmd/env_detection.go
  cli/cmd/root.go
  main.go
Labels: improve

#684 feat: Enrich addr info with remote addr info
  kern/common.h
  kern/openssl.h
  pkg/event_processor/base_event.go
  user/event/event_openssl.go
  user/module/probe_openssl.go
  user/module/probe_openssl_text.go
Labels: enhancement

#687 fix ecapture docker images CVE-2024-24790
  .github/workflows/codeql-analysis.yml
  .github/workflows/go-c-cpp.yml
  .github/workflows/release.yml
  builder/Dockerfile
  builder/init_env.sh
Labels: fix, improve

#686 fix #685, the Processor print "incoming chan is full",and exit.
  cli/cmd/root.go
  pkg/event_processor/iworker.go
  pkg/event_processor/processor.go
  user/module/imodule.go
  user/module/probe_openssl.go
Labels: 🐞 bug, fix

#688 feat: Support for new version detection feature.
  COMPILATION_CN.md
  cli/cmd/root.go
  cli/cmd/upgrade.go
  pkg/upgrade/github_response.go
  pkg/upgrade/upgrade.go
  pkg/upgrade/upgrade_test.go
  variables.mk
Labels: documentation, enhancement, improve

#695 fix: use other hooks to probe 5-tuple
  kern/openssl.h
  user/module/probe_openssl_text.go
Labels: enhancement, fix

#698 Limit github action serialization and increase CI caching function
  .github/workflows/release.yml
  go.mod
  go.sum
Labels: enhancement, dependencies

#704 fix : add openssl_3_1_0 target
  variables.mk
Labels: invalid, fix

#708 fix #697, When building in nocore mode, use only non-core bytecode les by default.
  Makefile
  cli/cmd/root.go
  cli/cmd/upgrade.go
  functions.mk
  pkg/upgrade/upgrade_test.go
  user/config/iconfig.go
  user/module/imodule.go
  variables.mk
Labels: fix

#707 fix: check CAP_BPF by capget syscall
  cli/cmd/env_detection.go
  cli/cmd/root.go
Labels: fix

#709 fixed the issue of missing cross-compilation environment.
  .github/workflows/release.yml
Labels: 🐞 bug

#710 fix(ci): fix github action release notes generation
  .github/workflows/release.yml
  go.sum
Labels: dependencies, Review effort [1-5]: 2
