Repository gojue/ecapture, pull requests merged in 2024-09, with the labels that each got.

#616 chore: Use `-tags 'netgo'` in bulding process to avoid SIGSEGV because of the different version of glibc in dfferent Linux distros
  .gitignore
  functions.mk
Labels: fix

#619 feat: remove tcp packet limitation
  kern/tc.h
  user/module/probe_openssl_pcap.go
Labels: enhancement

#624 kern: support openssl 3.3.2/3.2.3/3.1.7/3.0.15
  kern/openssl_3_1_0_kern.c
  kern/openssl_3_2_3_kern.c
  kern/openssl_3_3_0_kern.c
  user/module/probe_openssl_lib.go
  utils/openssl_offset_3.0.sh
  utils/openssl_offset_3.1.sh
  utils/openssl_offset_3.2.sh
  utils/openssl_offset_3.3.sh
Labels: enhancement

#644 workflows: update linux source tgz file version.
  .github/workflows/codeql-analysis.yml
  .github/workflows/go-c-cpp.yml
  .github/workflows/release.yml
  COMPILATION.md
  COMPILATION_CN.md
  README_JA.md
  builder/init_env.sh
  variables.mk
Labels: bug
