Repository gojue/ecapture, pull requests merged in 2024-11, with the labels that each got.

#660 feat(user/module): add ossl version 3.4.0 support
  kern/openssl_3_4_0_kern.c
  user/module/probe_openssl_lib.go
  utils/openssl_3_2_0_offset.c
  utils/openssl_offset_3.4.sh
  variables.mk
Labels: enhancement, good first issue

#654 feat: support keylog and pcap mode in gnutls
  cli/cmd/gnutls.go
  kern/gnutls.h
  kern/gnutls_3_6_12_kern.c
  kern/gnutls_3_6_14_kern.c
  kern/gnutls_3_7_0_kern.c
  kern/gnutls_3_7_3_kern.c
  kern/gnutls_3_7_7_kern.c
  kern/gnutls_3_8_4_kern.c
  kern/gnutls_3_8_7_kern.c
  kern/gnutls_masterkey.h
  user/config/config_gnutls.go
  user/config/config_gnutls_linux.go
  user/event/event_mastersecret_gnutls.go
  user/module/probe_gnutls.go
  user/module/probe_gnutls_keylog.go
  user/module/probe_gnutls_lib.go
  user/module/probe_gnutls_pcap.go
  user/module/probe_gnutls_text.go
  utils/gnutls_offset.c
  utils/gnutls_offset.sh
  variables.mk
Labels: enhancement, improve

#665 Fix the parameter error issue of the uprobe type hook.
  COMPILATION_CN.md
  pkg/event_processor/processor.go
  user/module/probe_bash.go
  user/module/probe_gotls_text.go
  user/module/probe_mysqld.go
  user/module/probe_openssl.go
Labels: bug

#666 chore: remove unused flags `BuildRequires` in rpmBuild.spec
  CHANGELOG.md
  README.md
  README_CN.md
  README_JA.md
  builder/rpmBuild.spec
  cli/cmd/gnutls.go
  cli/cmd/nss.go
  cli/cmd/tls.go
  images/ecapture-help-v0.8.9.svg
  images/openssl-example.jpg
  images/wechat-group.jpg
  user/module/probe_gnutls_keylog.go
Labels: documentation, enhancement, improve
