Repository gojue/ecapture, pull requests merged in 2024-05, with the labels that each got.

#536 makefile: Optimized the generation mechanism of kernel header files
  builder/init_env.sh
  cli/cmd/root.go
  variables.mk
Labels: improve

#537 add dockerfile
  .github/workflows/release.yml
  README.md
  README_CN.md
  README_JA.md
  builder/Dockerfile
Labels: enhancement

#539 cli: Use a formatted logger rs/zerolog
  cli/cmd/bash.go
  cli/cmd/global.go
  cli/cmd/gnutls.go
  cli/cmd/gotls.go
  cli/cmd/mysqld.go
  cli/cmd/nss.go
  cli/cmd/postgres.go
  cli/cmd/root.go
  cli/cmd/tls.go
  functions.mk
  go.mod
  go.sum
  pkg/event_processor/base_event.go
  pkg/event_processor/http_response.go
  pkg/event_processor/iparser.go
  pkg/event_processor/iworker.go
  pkg/event_processor/processor.go
  pkg/event_processor/processor_test.go
  pkg/util/ebpf/bpf.go
  user/config/common.go
  user/config/common_linux.go
  user/config/config_bash.go
  user/config/config_gnutls.go
  user/config/config_gnutls_linux.go
  user/config/config_gotls.go
  user/config/config_mysqld.go
  user/config/config_nspr.go
  user/config/config_nspr_linux.go
  user/config/config_openssl.go
  user/config/config_openssl_linux.go
  user/config/config_postgres.go
  user/config/const.go
  user/config/iconfig.go
  user/event/event_masterkey.go
  user/module/imodule.go
  user/module/probe_bash.go
  user/module/probe_gnutls.go
  user/module/probe_gotls.go
  user/module/probe_gotls_keylog.go
  user/module/probe_gotls_pcap.go
  user/module/probe_gotls_text.go
  user/module/probe_mysqld.go
  user/module/probe_nspr.go
  user/module/probe_openssl.go
  user/module/probe_openssl_keylog.go
  user/module/probe_openssl_lib.go
  user/module/probe_openssl_pcap.go
  user/module/probe_openssl_text.go
  user/module/probe_pcap.go
  user/module/probe_postgres.go
Labels: enhancement, improve

#540 utils: supported openssl 1.1.1w, 3.0.13, 3.1.5, 3.2.1
  user/module/probe_openssl_lib.go
  utils/openssl_offset_1.1.1.sh
  utils/openssl_offset_3.0.sh
  utils/openssl_offset_3.1.sh
  utils/openssl_offset_3.2.sh
Labels: enhancement

#546 user: fixed #542, masterkey being written to pcapng multiple times.
  user/module/probe_openssl.go
  user/module/probe_pcap.go
Labels: fix

#547 cli: fix undefined: config.MysqldConfig. (fix #548)
  .github/workflows/go-c-cpp.yml
  cli/http/server.go
  cli/http/server_androidgki.go
  cli/http/server_linux.go
Labels: bug, fix

#554 user: fix #553, `hashLen` is not allowed to be more than 64 bytes
  user/module/imodule.go
  user/module/probe_openssl.go
Labels: fix

#556 cli: update docker usage
  cli/cmd/root.go
  cli/cmd/tls.go
Labels: documentation

#555 kern: Support for the non-Android boringssl library has been added.
  kern/boringssl_na_kern.c
  user/module/probe_openssl_lib.go
  utils/boringssl_non_android_offset.sh
  variables.mk
Labels: enhancement

#557 user: format clientRandom string in gotls module
  user/module/probe_gotls.go
Labels: improve
