Repository gojue/ecapture, pull requests merged in 2024-06, with the labels that each got.

#563 workflows: add Qodana
  .github/workflows/code_quality.yml
Labels: improve, dependencies

#566 fix create output.log failed.
  cli/cmd/root.go
Labels: bug, fix

#567 pkg: fix send on closed channel
  pkg/event_processor/processor.go
  user/module/imodule.go
Labels: bug, fix

#572 fix: DumpResponse error in HEAD request
  pkg/event_processor/http_response.go
Labels: bug, fix

#573 fix: truncated body dump error
  pkg/event_processor/http_request.go
  pkg/event_processor/http_response.go
Labels: enhancement
