Repository gojue/ecapture, pull requests merged in 2024-10, with the labels that each got.

#646 fix the issue with retrieving the return value of the Read function in the Golang TLS module.
  kern/bash_kern.c
  kern/boringssl_masterkey.h
  kern/common.h
  kern/gnutls_kern.c
  kern/gotls_kern.c
  kern/mysqld_kern.c
  kern/nspr_kern.c
  kern/openssl_3_2_0_kern.c
  kern/openssl_3_2_3_kern.c
  kern/openssl_3_3_0_kern.c
  kern/openssl_masterkey.h
  kern/openssl_masterkey_3.0.h
  kern/openssl_masterkey_3.2.h
  user/module/probe_gotls_text.go
  utils/boringssl-offset.c
  utils/openssl_1_0_2_offset.c
  utils/openssl_1_1_0_offset.c
  utils/openssl_1_1_1_offset.c
  utils/openssl_3_0_offset.c
  utils/openssl_3_2_0_offset.c
  variables.mk
Labels: bug, enhancement, fix

#648 builder: docerk build error: header not found (fix: #649)
  Makefile
  builder/Dockerfile
  builder/init_env.sh
  variables.mk
Labels: bug, fix

#641 typo: 3中 --> 3种
  README_CN.md
  README_JA.md
Labels: documentation

#642 fix: SSLDataEvent's fd is 0 Error
  kern/boringssl_a_13_kern.c
  kern/boringssl_a_14_kern.c
  kern/boringssl_na_kern.c
  kern/openssl.h
  kern/openssl_1_0_2a_kern.c
  kern/openssl_1_1_0a_kern.c
  kern/openssl_1_1_1a_kern.c
  kern/openssl_1_1_1b_kern.c
  kern/openssl_1_1_1d_kern.c
  kern/openssl_1_1_1j_kern.c
  kern/openssl_3_0_0_kern.c
  kern/openssl_3_1_0_kern.c
  kern/openssl_3_2_0_kern.c
  kern/openssl_3_2_3_kern.c
  kern/openssl_3_3_0_kern.c
  user/event/event_openssl.go
  user/module/probe_openssl.go
  utils/boringssl-offset.c
  utils/openssl_1_0_2_offset.c
  utils/openssl_1_1_0_offset.c
  utils/openssl_1_1_1_offset.c
  utils/openssl_3_0_offset.c
  utils/openssl_3_2_0_offset.c
Labels: enhancement, fix
