Repository gojue/ecapture, pull requests merged in 2024-04, with the labels that each got.

#516 [Fix] get textStart from pclnTable
  user/config/config_gotls.go
Labels: bug, fix

#517 fix: amd64, offset read error issue for PIE executable. PR #516
  user/config/config_gotls.go
Labels: fix

#521 user: return error when detect openssl version failed.
  user/module/probe_openssl_lib.go
Labels: bug

#525 readme: improve English README.md translation and add TOCs
  README.md
  README_CN.md
  README_JA.md
Labels: documentation

#530 chore: rename ecapture module name.
  cli/cmd/bash.go
  cli/cmd/gnutls.go
  cli/cmd/gotls.go
  cli/cmd/mysqld.go
  cli/cmd/nss.go
  cli/cmd/postgres.go
  cli/cmd/root.go
  cli/cmd/tls.go
  cli/main.go
  go.mod
  main.go
  pkg/event_processor/base_event.go
  pkg/event_processor/iworker.go
  pkg/event_processor/processor.go
  user/config/iconfig.go
  user/module/imodule.go
  user/module/probe_bash.go
  user/module/probe_gnutls.go
  user/module/probe_gotls.go
  user/module/probe_gotls_keylog.go
  user/module/probe_gotls_pcap.go
  user/module/probe_gotls_text.go
  user/module/probe_mysqld.go
  user/module/probe_nspr.go
  user/module/probe_openssl.go
  user/module/probe_openssl_keylog.go
  user/module/probe_openssl_lib.go
  user/module/probe_openssl_pcap.go
  user/module/probe_openssl_text.go
  user/module/probe_pcap.go
  user/module/probe_postgres.go
  variables.mk
Labels: documentation, dependencies
