Repository gojue/ecapture, pull requests merged in 2025-03, with the labels that each got.

#731 improve: provide opts to set the truncate size in text mode to reduce memory cost
  Makefile
  cli/cmd/root.go
  pkg/event_processor/iworker.go
  pkg/event_processor/processor.go
  pkg/event_processor/processor_test.go
  user/config/iconfig.go
  user/module/imodule.go
Labels: improve

#745 improve: handle COMPRESSION_ERROR to reduce the error log displayed
  pkg/event_processor/http2_request.go
  pkg/event_processor/http2_response.go
Labels: improve

#741 fix: #739 the tuple to be unreachable.
  user/module/probe_openssl.go
Labels: fix

#748 improve: add frame length
  pkg/event_processor/http2_request.go
  pkg/event_processor/http2_response.go
Labels: fix, lgtm

#750 fix: #739 Add sock consistency check to void tuple miss.
  user/module/probe_openssl.go
Labels: fix, lgtm

#758 fix: #757 , update clang version to 10 in installation scripts
  .github/workflows/go-c-cpp.yml
  builder/init_env.sh
Labels: 🐞 bug, fix
