Repository gojue/ecapture, pull requests merged in 2025-05, with the labels that each got.

#769 feat: add support for OpenSSL 3.3.3 and 3.4.1, update version mappings
  go.mod
  go.sum
  kern/openssl_3_2_4_kern.c
  kern/openssl_3_3_3_kern.c
  kern/openssl_3_4_1_kern.c
  user/module/probe_openssl_lib.go
  utils/openssl_offset_3.1.sh
  utils/openssl_offset_3.2.sh
  utils/openssl_offset_3.3.sh
  utils/openssl_offset_3.4.sh
  variables.mk
Labels: 🐞 bug, enhancement, dependencies

#775 opt: redesign the truncate effect logic to reduce memory cost in text mode #718
  pkg/event_processor/iworker.go
Labels: enhancement, lgtm

#777 fix: clean up SSLDataEvent string methods and improve logging #776
  pkg/event_processor/base_event.go
  user/event/event_gnutls.go
  user/event/event_nspr.go
  user/event/event_openssl.go
  user/module/imodule.go
  user/module/probe_openssl.go
Labels: 🐞 bug, fix, improve

#786 fix: avoid writing empty decryption secrets block in savePcapng method
  user/module/probe_pcap.go
Labels: 🐞 bug
