Repository gojue/ecapture, pull requests merged in 2025-06, with the labels that each got.

#793 feat: add JetBrains logo and acknowledgements to README files
  README.md
  README_CN.md
  README_JA.md
Labels: documentation, size:S

#792 feat: define early_secret in SSL structures for enhanced security
  .gitignore
  builder/rpmBuild.spec
  kern/boringssl_masterkey.h
  kern/common.h
  kern/gotls_kern.c
  kern/openssl_1_0_2a_kern.c
  kern/openssl_1_1_0a_kern.c
  kern/openssl_1_1_1a_kern.c
  kern/openssl_1_1_1b_kern.c
  kern/openssl_1_1_1d_kern.c
  kern/openssl_1_1_1j_kern.c
  kern/openssl_3_0_0_kern.c
  kern/openssl_3_1_0_kern.c
  kern/openssl_3_2_0_kern.c
  kern/openssl_3_2_3_kern.c
  kern/openssl_3_2_4_kern.c
  kern/openssl_3_3_0_kern.c
  kern/openssl_3_3_2_kern.c
  kern/openssl_3_3_3_kern.c
  kern/openssl_3_4_0_kern.c
  kern/openssl_3_4_1_kern.c
  kern/openssl_3_5_0_kern.c
  kern/openssl_masterkey.h
  kern/openssl_masterkey_3.0.h
  kern/openssl_masterkey_3.2.h
  kern/zsh_kern.c
  pkg/util/hkdf/hkdf.go
  user/event/event_masterkey.go
  user/module/probe_openssl.go
  utils/gnutls_offset.c
  utils/openssl_1_1_1_offset.c
  utils/openssl_3_0_offset.c
  utils/openssl_3_2_0_offset.c
  utils/openssl_3_5_0_offset.c
  utils/openssl_offset_1.0.2.sh
  utils/openssl_offset_1.1.0.sh
  utils/openssl_offset_1.1.1.sh
  utils/openssl_offset_3.0.sh
  utils/openssl_offset_3.1.sh
  utils/openssl_offset_3.2.sh
  utils/openssl_offset_3.3.sh
  utils/openssl_offset_3.4.sh
  utils/openssl_offset_3.5.sh
  variables.mk
Labels: enhancement, size:L

#801 feat: support gnutls early secret
  kern/gnutls_3_6_12_kern.c
  kern/gnutls_3_6_13_kern.c
  kern/gnutls_3_7_0_kern.c
  kern/gnutls_3_7_3_kern.c
  kern/gnutls_3_7_7_kern.c
  kern/gnutls_3_8_4_kern.c
  kern/gnutls_3_8_7_kern.c
  kern/gnutls_masterkey.h
  user/event/event_mastersecret_gnutls.go
  user/module/probe_gnutls_keylog.go
  user/module/probe_gnutls_lib.go
  utils/gnutls_offset.c
  utils/gnutls_offset.sh
  variables.mk
Labels: enhancement, lgtm, size:L

#805 fix: Improve bash path detection and correct probe attachment
  user/config/config_bash.go
  user/module/probe_bash.go
Labels: lgtm, size:M
