Repository gojue/ecapture, pull requests merged in 2025-01, with the labels that each got.

#713 fix(make): improve error handling and clean target logic in Makefile
  Makefile
  builder/init_env.sh
  functions.mk
Labels: fix, improve, Review effort [1-5]: 4

#715 fix: incorrect CAP_BPF check method
  cli/cmd/env_detection.go
Labels: 🐞 bug, Review effort [1-5]: 2, lgtm

#722 feat(ci): update GitHub Action runners with Linux arm64 host
  .github/workflows/go-c-cpp.yml
Labels: enhancement, Review effort [1-5]: 4
